# Generated by Django 3.1.4 on 2021-01-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201231_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
