# Generated by Django 3.1.4 on 2021-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210107_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('T', 'Tshirts'), ('P', 'Pants'), ('SH', 'Shoe'), ('J', 'Jeans'), ('WD', 'Womens dress'), ('SKRT', 'Skirt')], max_length=5),
        ),
    ]
