# Generated by Django 3.1.4 on 2020-12-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
