# Generated by Django 3.1.4 on 2020-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Coupon',
            new_name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
