# Generated by Django 3.1.4 on 2020-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
