# Generated by Django 3.1.4 on 2020-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201228_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=132456, max_length=20),
            preserve_default=False,
        ),
    ]
